import {createClient} from '@supabase/supabase-js';import {runtimeState,recommendNext} from './activity-runtime.mjs';import {renderActivity} from './activity-renderer.mjs';import {resolveEnrollment} from './enrollment-session.mjs';import {loadActivityRecords,submitEvidence} from './evidence-session.mjs';import {loadSkillMeasurements,summarizeSkills} from './skill-session.mjs';import {submitOfficialAssessment} from './enrollment-session.mjs';
const client=createClient('https://ktkdcfxeaicbykdurlfg.supabase.co','sb_publishable_P6NrKFErT6ntjXg2UMWbPw_OtRapbiF');
const course=await fetch('/assets/reference/customer-service-reference.json').then(r=>{if(!r.ok)throw new Error('تعذر تحميل الدورة');return r.json()});
let records=[],current=0;const qs=new URLSearchParams(location.search),enrollmentId=qs.get('enrollment');const session=await resolveEnrollment(client,enrollmentId,course.slug,course.version);if(session.kind==='signed-out')location.href='/login';let skillRows=[];if(session.kind==='enrolled'){records=await loadActivityRecords(client,session,course);skillRows=await loadSkillMeasurements(client,session)}
const title=document.getElementById('course-title'),activity=document.getElementById('activity'),nav=document.getElementById('activity-nav'),skills=document.getElementById('skills'),progressValue=document.getElementById('progress-value'),progressBar=document.getElementById('progress-bar'),message=document.getElementById('activity-message'),primary=document.getElementById('primary-action'),previous=document.getElementById('previous'),coachTitle=document.getElementById('coach-title'),coachCopy=document.getElementById('coach-copy'),measurement=document.getElementById('measurement');
title.textContent=course.title;function renderSkills(){skills.replaceChildren();const summaries=summarizeSkills(course,skillRows);for(const item of summaries){const el=document.createElement('div');el.className='skill';const delta=item.delta==null?'':(' · '+(item.delta>=0?'+':'')+item.delta+' نقطة');el.textContent=item.title+(item.post==null?'':(' · '+item.post+'%'))+delta;skills.append(el)}}renderSkills();
function state(){return runtimeState({slug:course.slug,version:course.version,activities:course.activities},records)}
function render(){const st=state(),a=st.activities[current];activity.innerHTML=renderActivity(a);nav.replaceChildren();st.activities.forEach((item,i)=>{const b=document.createElement('button');b.className='activity-link';b.dataset.state=item.state;b.setAttribute('aria-current',i===current?'true':'false');b.innerHTML='<span class="dot"></span><span>'+(i+1)+'. '+item.title+'</span>';b.addEventListener('click',()=>{if(i<=firstBlockedIndex(st))current=i;render()});nav.append(b)});const done=st.activities.filter(x=>x.state==='completed').length,pct=Math.round(done/st.activities.length*100);progressValue.textContent=pct+'%';progressBar.style.width=pct+'%';previous.disabled=current===0;primary.textContent=a.type==='assessment'?'ابدأ التقييم الرسمي':needsEvidence(a.type)?'أرسل للمراجعة':'أكمل النشاط';const rec=recommendNext(st);coachTitle.textContent=rec.kind==='remediate'?'راجع وحسّن تطبيقك':rec.kind==='wait_review'?'بانتظار المراجعة':rec.kind==='complete'?'أكملت الرحلة':'خطوتك التالية';coachCopy.textContent=rec.kind==='wait_review'?'أرسلت المهمة بنجاح. لا نعتبرها مجتازة حتى تتم مراجعتها.':rec.kind==='remediate'?'راجع الملاحظات ثم أعد المحاولة.':'ركز على النشاط الحالي ثم انتقل لما بعده.';measurement.innerHTML=(a.skillCodes||[]).map(code=>'<div class="measure">'+(course.skills.find(s=>s.code===code)?.title||code)+'</div>').join('')}
function firstBlockedIndex(st){const i=st.activities.findIndex(x=>x.required!==false&&x.state!=='completed');return i<0?st.activities.length-1:i}
function needsEvidence(t){return['reflection','practical_task','file_evidence'].includes(t)}
previous.addEventListener('click',()=>{if(current>0){current--;render()}});
primary.addEventListener('click',async()=>{const st=state(),a=st.activities[current];message.textContent='';if(a.type==='assessment'){if(session.kind!=='enrolled'){message.textContent='التقييم الرسمي متاح فقط من دورة مسجلة في حسابك.';return}message.textContent='التقييم الرسمي جاهز تقنيًا، ويحتاج بنك أسئلة النسخة المعتمد قبل الإرسال.';return}if(needsEvidence(a.type)){const input=activity.querySelector('[data-evidence]');if(!input||(!input.value&&input.type!=='file')){message.textContent='أكمل التطبيق قبل الإرسال.';return}if(session.kind!=='enrolled'){message.textContent='حفظ التطبيق يتطلب فتح الدورة من حسابك.';return}const payload=input.type==='file'?{file_name:input.files?.[0]?.name||''}:{response:input.value};const saved=await submitEvidence(client,session,course,a,payload);records=records.filter(r=>r.activity_key!==a.key);records.push(saved);message.textContent='تم إرسال التطبيق للمراجعة.'}else{records=records.filter(r=>r.activity_key!==a.key);records.push({activity_key:a.key,completed_at:new Date().toISOString()});message.textContent=session.kind==='enrolled'?'تم إكمال النشاط.':'اكتمل النشاط في العرض العام دون حفظ التقدم.';if(current<course.activities.length-1)current++}render()});
document.getElementById('exit-course').addEventListener('click',()=>location.href='/workspace');render();