const escape = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]);
const pathFor = (course) => `/catalog/${encodeURIComponent(course.slug)}`;
const list = (items) => `<ul>${items.map((item) => `<li>${escape(item)}</li>`).join('')}</ul>`;

function document(title, content, page) {
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} | كفو</title><meta name="description" content="مواد تعليمية مجانية لتطوير مهارات العمل في كفو"><link rel="stylesheet" href="/assets/fonts.css"><link rel="stylesheet" href="/assets/learning.css"><script type="module" src="/assets/course.js"></script></head><body data-learning-page="${page}"><a class="skip" href="#main">انتقل إلى المحتوى</a><header class="site-header"><a class="brand" href="/" aria-label="كفو — الرئيسية"><img src="/upload/logo.png" width="108" height="48" alt="كفو"></a><nav aria-label="التنقل الرئيسي"><a href="/">الرئيسية</a><a href="/catalog" aria-current="page">الدورات</a><a href="/workspace">مساحة العمل</a></nav></header>${content}<footer class="site-footer">كفو · مهارات تتعلمها وتطبقها في عملك</footer></body></html>`;
}

export function renderCatalogue(courses) {
  const cards = courses.map((course, index) => `<article class="course-card" data-course-card data-search="${escape(`${course.title} ${course.summary} ${course.objectives.join(' ')}`)}"><div class="card-top"><span class="badge">مجانية</span><span class="course-number">${String(index + 1).padStart(2, '0')}</span></div><h2><a href="${pathFor(course)}">${escape(course.title)}</a></h2><p>${escape(course.summary)}</p><div class="card-bottom"><span>${course.lessons.length} دروس · مراجعة ذاتية</span><a class="button" href="${pathFor(course)}">استكشف الدورة</a></div></article>`).join('');
  return document('الدورات المجانية', `<main id="main" class="catalogue"><section class="catalogue-intro"><span class="eyebrow">تعلم بخطوات عملية</span><h1>اكتشف ما يطوّر مهاراتك</h1><p>دورات مجانية باللغة العربية، مع أمثلة وتمارين تساعدك على تحويل الفكرة إلى ممارسة.</p></section><section class="course-directory" aria-label="الدورات"><div class="directory-heading"><h2>اختر ما تريد تطويره</h2><span id="course-count" role="status">${courses.length} دورات</span></div><label class="search-label" for="course-search">ابحث عن دورة أو مهارة</label><input id="course-search" class="search" type="search" placeholder="مثال: التواصل، إدارة الوقت" autocomplete="off"><div class="course-grid">${cards}</div><p id="search-empty" class="empty-state" hidden>لا توجد دورة مطابقة. جرّب كلمة أخرى.</p></section></main>`, 'catalogue');
}

export function renderCourse(course) {
  const lessons = course.lessons.map((lesson, index) => `<section class="lesson" id="lesson-${escape(lesson.id)}" data-lesson><span class="eyebrow">الدرس ${index + 1} من ${course.lessons.length}</span><h2>${escape(lesson.title)}</h2>${lesson.body.map((paragraph) => `<p>${escape(paragraph)}</p>`).join('')}<aside class="practice"><h3>جرّبها في عملك</h3><p>${escape(lesson.exercise)}</p></aside><div class="lesson-navigation">${index > 0 ? `<a href="#lesson-${escape(course.lessons[index - 1].id)}">الدرس السابق</a>` : '<a href="#overview">عن الدورة</a>'}${index + 1 < course.lessons.length ? `<a class="button" href="#lesson-${escape(course.lessons[index + 1].id)}">الدرس التالي</a>` : '<a class="button" href="#review">انتقل للمراجعة الذاتية</a>'}</div></section>`).join('');
  const questions = course.assessment.questions.map((question, index) => `<fieldset data-question data-correct="${question.correctIndex}"><legend><span class="question-number">${index + 1}.</span> ${escape(question.prompt)}</legend>${question.options.map((option, optionIndex) => `<label class="answer"><input type="radio" name="question-${index}" value="${optionIndex}" required><span>${escape(option)}</span></label>`).join('')}<p class="answer-feedback" hidden data-explanation="${escape(question.explanation)}"></p></fieldset>`).join('');
  const content = `<main id="main" class="course-shell"><a class="back-link" href="/catalog">جميع الدورات</a><div class="course-layout"><aside class="course-sidebar"><details open><summary>محتوى الدورة</summary><nav aria-label="محتوى الدورة"><a href="#overview">عن الدورة</a>${course.lessons.map((lesson, index) => `<a href="#lesson-${escape(lesson.id)}"><span>${index + 1}</span>${escape(lesson.title)}</a>`).join('')}<a href="#review">المراجعة الذاتية</a></nav></details></aside><div class="course-reading"><section id="overview" class="course-overview"><span class="badge">دورة مجانية · ${course.lessons.length} دروس</span><h1>${escape(course.title)}</h1><p class="lead">${escape(course.summary)}</p><h2>ماذا ستتعلم؟</h2><div class="objectives">${list(course.objectives)}</div><a class="button" href="#lesson-${escape(course.lessons[0].id)}">ابدأ التعلم</a><p class="learning-note">يمكنك قراءة الدروس دون تسجيل الدخول. المراجعة الذاتية للتدرب على ما تعلمته؛ لا تمنح شهادة أو تسجل إنجازًا في حسابك.</p></section>${lessons}<section id="review" class="review"><span class="eyebrow">اختبر فهمك</span><h2>مراجعة ذاتية</h2><p>اختر إجابة لكل سؤال، ثم راجع التفسير. تبقى إجاباتك في هذه الصفحة فقط وتُمسح عند إعادة تحميلها.</p><form id="self-check">${questions}<p id="review-result" class="review-result" role="status" tabindex="-1" hidden></p><div class="review-actions"><button class="button" type="submit">راجع إجاباتي</button><button class="secondary-button" type="reset">حاول مجددًا</button></div></form></section></div></div></main>`;
  return document(course.title, content, 'course');
}
